#!/bin/bash
# Generated by sync-roadmap-to-gh.js --dry-run
# Run: gh auth refresh -s project first

gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E1 — Fundacional: Repo, padrões e documentação mínima' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E2 — Config & Model (MVP = JSON)' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E3 — Core Engine: executor, erros, health' --body '**Nota (arquitetura atual):** O executor existe no BACK via `routes/devices.js` e controllers — roteamento de comandos por device e execução via adapters (tuya.js, winix.js). Não há `core/executor.py`; a lógica está distribuída no Node.' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E4 — Plugin System (MCP-like v0)' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E5 — Dispositivos: Tuya + Winix (valor real)' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E6 — UI Web (MVP sólido)' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E7 — Scenes avançadas (pós-MVP incremental)' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E8 — Pesquisa técnica (Spikes) — validar hipóteses' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E9 — Integrações “Alexa-like” (pós-MVP)' --body '- Widgets: RSS, weather, commute time
- Media: Spotify control, YouTube launcher' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'E10 — Estabilidade e Observabilidade mínima' --body '(no description)' --label 'roadmap' --label 'epic' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F1.1 — Estrutura do repo e scripts de execução' --body '## F1.1 — Estrutura do repo e scripts de execução
### S1.1.1 — Criar estrutura base do repositório' --label 'roadmap' --label 'feature' --label 'epic:E1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F1.2 — ADRs (Decisões arquiteturais)' --body '## F1.2 — ADRs (Decisões arquiteturais)
### S1.2.1 — Registrar ADR base: LAN-first + plugin-first + core mínimo' --label 'roadmap' --label 'feature' --label 'epic:E1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F2.1 — Schemas mínimos + validação leve' --body '## F2.1 — Schemas mínimos + validação leve
### S2.1.1 — Definir `rooms.json`
### S2.1.2 — Definir `devices.json`
### S2.1.3 — Definir `scenes.json` (DSL v0)
### S2.1.4 — Runtime state (separado do config)' --label 'roadmap' --label 'feature' --label 'epic:E2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F3.1 — Executor canônico (device/scene/macro)' --body '## F3.1 — Executor canônico (device/scene/macro)
### S3.1.1 — Implementar `execute_action(action)`
### S3.1.2 — Implementar `run_scene(sceneId)`' --label 'roadmap' --label 'feature' --label 'epic:E3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F3.2 — Errors padronizados' --body '## F3.2 — Errors padronizados
### S3.2.1 — Error model + mapping JSON' --label 'roadmap' --label 'feature' --label 'epic:E3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F3.3 — Health/Heartbeat mínimo' --body '## F3.3 — Health/Heartbeat mínimo
### S3.3.1 — Poller e status online/offline' --label 'roadmap' --label 'feature' --label 'epic:E3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F4.1 — Contrato adapter v0 + protocolo v1 (MCP-like)' --body '## F4.1 — Contrato adapter v0 + protocolo v1 (MCP-like)
### S4.1.1 — Adapter Protocol v0 (stdin/stdout JSON) + mapping no BACK
### S4.1.2 — Protocol v1 MCP-like (describe/read/invoke) + semantic hints' --label 'roadmap' --label 'feature' --label 'epic:E4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F4.2 — Registry por vendor/type' --body '## F4.2 — Registry por vendor/type
### S4.2.1 — Resolver plugin por `(vendor,type)`' --label 'roadmap' --label 'feature' --label 'epic:E4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F5.1 — Tuya Cloud (primeiro para funcionar rápido)' --body '## F5.1 — Tuya Cloud (primeiro para funcionar rápido)
### S5.1.1 — Tuya Cloud CLI (token/devices/status/functions/commands)
### S5.1.2 — Tuya Switch multi-gang (MVP device #1)
### S5.1.3 — Tuya Smart Plug (power)
### S5.1.4 — Tuya Light (power/brightness/rgb)
### S5.1.5 — Tuya IR + Sensor temp/umidade (climate_sensor_ir)
### S5.1.6 — LAN-first Tuya (fase 2)' --label 'roadmap' --label 'feature' --label 'epic:E5' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F5.2 — Winix purifier (MVP device #2)' --body '## F5.2 — Winix purifier (MVP device #2)
### S5.2.1 — Plugin Winix (stub/lib/api) end-to-end' --label 'roadmap' --label 'feature' --label 'epic:E5' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F6.1 — Navegação e telas' --body '## F6.1 — Navegação e telas
### S6.1.1 — Home (pinned + scenes + widgets mínimos)
### S6.1.2 — Devices (search + filter)
### S6.1.3 — Scenes
### S6.1.4 — Rooms' --label 'roadmap' --label 'feature' --label 'epic:E6' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F6.2 — Feedback (toasts) + menu/config + debug' --body '## F6.2 — Feedback (toasts) + menu/config + debug
### S6.2.1 — Toast lifecycle + coalesce
### S6.2.2 — Menu de configuração (bottom sheet)
### S6.2.3 — Debug panel (Step zero)
### S6.2.4 — Bugfix estrutural do UI atual' --label 'roadmap' --label 'feature' --label 'epic:E6' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F6.3 — Renderer genérico por `describe()` (pós-MVP)' --body '## F6.3 — Renderer genérico por `describe()` (pós-MVP)
### S6.3.1 — GenericControlRenderer' --label 'roadmap' --label 'feature' --label 'epic:E6' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F7.1 — Scenes v1: delay + retry' --body '## F7.1 — Scenes v1: delay + retry
### S7.1.1 — Delay/retry básicos' --label 'roadmap' --label 'feature' --label 'epic:E7' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F7.2 — Scenes v2: variáveis e condições (pós-MVP)' --body '## F7.2 — Scenes v2: variáveis e condições (pós-MVP)
### S7.2.1 — Vars + if (safe evaluator)' --label 'roadmap' --label 'feature' --label 'epic:E7' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F8.1 — Spike: Kiper portão' --body '## F8.1 — Spike: Kiper portão
**Status:** Backlog  
**Deliverable:** doc de viabilidade + riscos + recomendação.
**Tasks**
- T8.1.1 Checar API oficial/local
- T8.1.2 Se RE: mapear auth/replay/binding
- T8.1.3 Go/No-go doc' --label 'roadmap' --label 'feature' --label 'epic:E8' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F8.2 — Spike: câmera inteligente' --body '## F8.2 — Spike: câmera inteligente
**Status:** Backlog  
**Deliverable:** doc custo/benefício + arquitetura.' --label 'roadmap' --label 'feature' --label 'epic:E8' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F8.3 — Spike: estrutura vertical vs horizontal' --body '## F8.3 — Spike: estrutura vertical vs horizontal
**Status:** Backlog  
**Hipótese:** “feature slice por device module” reduz fricção.
**Tasks**
- T8.3.1 Branch POC “vertical”
- T8.3.2 Implementar tuya_switch em layout vertical
- T8.3.3 Comparar delta de mudança
- T8.3.4 ADR de recomendação' --label 'roadmap' --label 'feature' --label 'epic:E8' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F8.4 — Spike: MCP-like adapter↔backend' --body '## F8.4 — Spike: MCP-like adapter↔backend
**Status:** Backlog  
**Hipótese:** reduzir hardcode (4 vs 6 gangs).
**Tasks**
- T8.4.1 Formalizar spec `describe/read/invoke` v0
- T8.4.2 POC com tuya_switch
- T8.4.3 Medir redução de mudanças no backend
- T8.4.4 Recomendação (adotar/não/partial)
---' --label 'roadmap' --label 'feature' --label 'epic:E8' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F10.1 — Activity timeline exportável' --body '## F10.1 — Activity timeline exportável
**Status:** Backlog  
**Tasks**
- T10.1.1 Log de cada invoke/scene
- T10.1.2 Export JSON' --label 'roadmap' --label 'feature' --label 'epic:E10' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'F10.2 — Secrets hygiene + CI check' --body '## F10.2 — Secrets hygiene + CI check
**Status:** Backlog  
**Tasks**
- T10.2.1 Mask tokens em logs
- T10.2.2 Checagem CI “.env não commit”
---
```text
You are a senior PM + Tech Lead. Convert this Markdown backlog into a Kanban-ready plan.
Output requirements:
A) A Kanban board with columns: Backlog / Next / In Progress / Blocked / Done
B) Milestones: MVP / v1 / v2 (assign stories to each)
C) For each Story:
   - DoD (specific, testable)
   - Acceptance criteria (Given/When/Then)
   - Test plan (manual + automated if applicable)
   - Edge cases
   - Tasks (0.5–4h each) with explicit dependencies
D) Risk register with mitigations
Constraints:
- Keep product minimal, stable, plugin-first, LAN-first.
- MVP must include: Tuya multi-gang switch control + Winix purifier control + Scenes manual + UI with toasts/menu.
- Do not invent new features; only refine, clarify and organize.
```
---
- **(1) S3.3.1 Dependencies:** Atualizado de "E4 plugin system (read)" para "BACK adapter router (`routes/devices.js`) + adapters implementados (tuya.js, winix.js) e integração heartbeat existente".
- **(2) Scenes vs Executor:** Adicionada nota em E3 sobre executor no BACK (routes/controllers); S6.1.3 alterado de Done para In progress com nota "UI list done; execution engine pending".
- **(3) Plugin protocol v0 vs v1:** S4.1.1 renomeado para "Adapter Protocol v0 (stdin/stdout JSON) + mapping no BACK" com Tasks/Acceptance alinhados à implementação atual; criada S4.1.2 "Protocol v1 MCP-like (describe/read/invoke)" em Backlog.
- **(4) LAN-first scope:** Adicionada clarificação na Visão do Produto: "MVP: Tuya via Cloud; LAN-first entra no v1/v2 (com fallback)".' --label 'roadmap' --label 'feature' --label 'epic:E10' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S1.1.1 — Criar estrutura base do repositório' --body '### S1.1.1 — Criar estrutura base do repositório
**Status:** Done  
**Objetivo:** deixar claro onde fica core/plugins/ui/configs/scripts.

**Entregáveis:**
- Pastas base criadas
- `README.md` com setup local
- `.env.example` e `.gitignore` corretos

**Dependencies:** none

**Tasks**
- T1.1.1.1 Criar pastas: `core/`, `plugins/`, `ui/`, `configs/`, `scripts/`, `docs/adr/`
- T1.1.1.2 Criar `README.md` (setup python/node + como rodar)
- T1.1.1.3 Criar `.env.example` (sem valores reais)
- T1.1.1.4 Criar `.gitignore` (env, caches, logs)

**Acceptance criteria (Given/When/Then)**
- Given repo clonado, When seguir README, Then UI e backend sobem sem erro.
- Given `.env.example`, When copiar para `.env`, Then app roda sem vazar secrets.

**Test plan**
- Rodar UI local (dev) e backend local
- Validar que `.env` não é versionado

**Edge cases**
- Windows path / shells diferentes
- Versões de python/node divergentes

---' --label 'roadmap' --label 'story' --label 'epic:E1' --label 'feature:F1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S1.2.1 — Registrar ADR base: LAN-first + plugin-first + core mínimo' --body '### S1.2.1 — Registrar ADR base: LAN-first + plugin-first + core mínimo
**Status:** Backlog  
**Dependencies:** S1.1.1

**Tasks**
- T1.2.1.1 Criar `docs/adr/000-template.md`
- T1.2.1.2 Criar `docs/adr/001-core-principles.md`

**Acceptance**
- ADR explica decisões e trade-offs em até 2 páginas.

---' --label 'roadmap' --label 'story' --label 'epic:E1' --label 'feature:F1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S2.1.1 — Definir `rooms.json`' --body '### S2.1.1 — Definir `rooms.json`
**Status:** Done  
**Tasks**
- T2.1.1.1 Criar `configs/rooms.json` (`id,name,order`)
- T2.1.1.2 Validar ids únicos no load

**Acceptance**
- Rooms aparecem ordenadas na UI.

**Edge cases**
- Room sem `order` → default 0

---' --label 'roadmap' --label 'story' --label 'epic:E2' --label 'feature:F2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S2.1.2 — Definir `devices.json`' --body '### S2.1.2 — Definir `devices.json`
**Status:** Done  
**Campos mínimos (MVP)**
- `id`, `type`, `vendor`, `name`, `roomId`, `tags[]`, `pinned`, `config{}`

**Dependencies:** S1.1.1

**Tasks**
- T2.1.2.1 Criar `configs/devices.json` com:
  - 1 Tuya device real
  - 1 Winix device (placeholder ok)
- T2.1.2.2 Documentar enum inicial `type` (README)
- T2.1.2.3 Doc: “como adicionar um device” (README)

**Acceptance**
- Backend carrega `devices.json` sem erro.
- UI lista cards dos devices.

**Edge cases**
- `roomId` inválido → fallback “Unknown room”
- `type/vendor` sem plugin → UI mostra como “Unsupported” sem crash

---' --label 'roadmap' --label 'story' --label 'epic:E2' --label 'feature:F2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S2.1.3 — Definir `scenes.json` (DSL v0)' --body '### S2.1.3 — Definir `scenes.json` (DSL v0)
**Status:** Done  
**Campos mínimos**
- `id,name,icon,tags[],actions[]`
- `actions[]`: `kind=device|scene|macro`

**Dependencies:** S3.1.x (executor)

**Tasks**
- T2.1.3.1 Criar `configs/scenes.json` (3–4 scenes)
- T2.1.3.2 Validar referências (deviceId/sceneId)
- T2.1.3.3 Documentar formato actions (README)

**Acceptance**
- Scene executa steps e retorna resumo agregado.

---' --label 'roadmap' --label 'story' --label 'epic:E2' --label 'feature:F2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S2.1.4 — Runtime state (separado do config)' --body '### S2.1.4 — Runtime state (separado do config)
**Status:** Done  
**Objetivo:** diferenciar config (git) de estado (runtime).

**Tasks**
- T2.1.4.1 Criar estrutura runtime cache no backend:
  - `status`, `state`, `last_seen`, `last_error`

**Acceptance**
- UI consegue pedir “estado atual” sem depender do config.

---' --label 'roadmap' --label 'story' --label 'epic:E2' --label 'feature:F2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S3.1.1 — Implementar `execute_action(action)`' --body '### S3.1.1 — Implementar `execute_action(action)`
**Status:** In progress  
**Dependencies:** none (pode começar cedo)

**Tasks**
- T3.1.1.1 Criar `core/executor.py` com `execute_action`
- T3.1.1.2 Logs estruturados (start/end por step)
- T3.1.1.3 3 testes unitários:
  - macro com 2 steps
  - scene chama scene
  - unknown kind → erro amigável

**Acceptance**
- Macro executa em ordem.
- Erro em step não derruba execução; retorna partial result.

**Edge cases**
- Macro recursiva (scene chama scene) → guard de recursion depth

---' --label 'roadmap' --label 'story' --label 'epic:E3' --label 'feature:F3.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S3.1.2 — Implementar `run_scene(sceneId)`' --body '### S3.1.2 — Implementar `run_scene(sceneId)`
**Status:** Backlog  
**Dependencies:** S3.1.1 + S2.1.3

**Tasks**
- T3.1.2.1 Carregar scenes do JSON
- T3.1.2.2 Validar ids e montar trace
- T3.1.2.3 Retornar payload agregado (`steps_ok/failed/errors[]`)

**Acceptance**
- Rodar “Cheguei” altera estados e gera activity log.

---' --label 'roadmap' --label 'story' --label 'epic:E3' --label 'feature:F3.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S3.2.1 — Error model + mapping JSON' --body '### S3.2.1 — Error model + mapping JSON
**Status:** Backlog  
**Dependencies:** S3.1.x

**Tasks**
- T3.2.1.1 Criar `core/errors.py`: `Offline/Timeout/Unsupported/AuthRequired/ConfigError`
- T3.2.1.2 Mapper para payload JSON (sem stacktrace cru)
- T3.2.1.3 Testes: offline → erro correto

**Acceptance**
- Offline gera mensagem clara e toast “offline”.

---' --label 'roadmap' --label 'story' --label 'epic:E3' --label 'feature:F3.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S3.3.1 — Poller e status online/offline' --body '### S3.3.1 — Poller e status online/offline
**Status:** Done  
**Dependencies:** BACK adapter router (`routes/devices.js`) + adapters implementados (tuya.js, winix.js) e integração heartbeat existente.

**Tasks**
- T3.3.1.1 Loop a cada N sec: `read(device)` via plugin
- T3.3.1.2 Atualizar runtime cache (last_seen/error)
- T3.3.1.3 Endpoint batch para UI (ex.: `/devices/state`)

**Acceptance**
- UI mostra Online/Offline corretamente.

**Edge cases**
- timeouts em sequência → degrade + backoff simples

---' --label 'roadmap' --label 'story' --label 'epic:E3' --label 'feature:F3.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S4.1.1 — Adapter Protocol v0 (stdin/stdout JSON) + mapping no BACK' --body '### S4.1.1 — Adapter Protocol v0 (stdin/stdout JSON) + mapping no BACK
**Status:** Done  
**Dependencies:** E2 (models)

**Contrato v0 (implementado)**
- Adapters Python: stdin/stdout JSON com `status` (device_id) e `command` (set_power, set_switch_1..N)
- BACK: `adapters/tuya.js`, `adapters/winix.js` — `runTuyaAdapter`, `runWinixAdapter`; roteamento em `routes/devices.js`
- Heartbeat: `heartbeat.js` chama adapters para status online/offline

**Tasks**
- T4.1.1.1 Contrato documentado (ex.: `ADAPTERS/*/CONTRACT.md`)
- T4.1.1.2 Mapeamento device → adapter no BACK (isTuyaDevice, isWinixPurifier)
- T4.1.1.3 Stub para testes (TUYA_DRIVER=stub)

**Acceptance**
- Adapter responde status/command via stdin/stdout; BACK roteia corretamente.

---' --label 'roadmap' --label 'story' --label 'epic:E4' --label 'feature:F4.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S4.1.2 — Protocol v1 MCP-like (describe/read/invoke) + semantic hints' --body '### S4.1.2 — Protocol v1 MCP-like (describe/read/invoke) + semantic hints
**Status:** Backlog  
**Dependencies:** S4.1.1

**Objetivo:** descoberta dinâmica de comandos sem hardcode de canais.

**Contrato v1 (planejado)**
- `describe(device)` → capabilities + commands + semantic hints
- `read(device)` → state normalizado + status
- `invoke(device, command, args)` → executa

**Tasks**
- T4.1.2.1 Formalizar schema v1 em `docs/protocol_v1.md`
- T4.1.2.2 Implementar `describe` em pelo menos um adapter (Tuya)
- T4.1.2.3 Migrar BACK router para usar describe (sem hardcode 4 vs 6 gangs)
- T4.1.2.4 Atualizar UI para consumir commands dinâmicos

**Acceptance**
- Backend descobre comandos dinamicamente via describe; UI renderiza sem hardcode de canais.

---' --label 'roadmap' --label 'story' --label 'epic:E4' --label 'feature:F4.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S4.2.1 — Resolver plugin por `(vendor,type)`' --body '### S4.2.1 — Resolver plugin por `(vendor,type)`
**Status:** Done  
**Dependencies:** S4.1.1

**Tasks**
- T4.2.1.1 Criar `core/registry.py`
- T4.2.1.2 Roteamento: device instance → plugin correto
- T4.2.1.3 Unsupported → erro amigável

**Acceptance**
- Device sem plugin vira “unsupported” sem quebrar app.

---' --label 'roadmap' --label 'story' --label 'epic:E4' --label 'feature:F4.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S5.1.1 — Tuya Cloud CLI (token/devices/status/functions/commands)' --body '### S5.1.1 — Tuya Cloud CLI (token/devices/status/functions/commands)
**Status:** Done  
**Dependencies:** E1

**Tasks**
- T5.1.1.1 `scripts/tuya_cloud_cli.py` no repo
- T5.1.1.2 `docs/tuya/setup.md`: link account, region, token
- T5.1.1.3 “Golden commands” no docs (copiar e colar)

**Acceptance**
- Você consegue listar devices e ler status/functions via CLI.

**Edge cases**
- lista vazia por falta de “Link Tuya App Account” → doc troubleshooting

---' --label 'roadmap' --label 'story' --label 'epic:E5' --label 'feature:F5.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S5.1.2 — Tuya Switch multi-gang (MVP device #1)' --body '### S5.1.2 — Tuya Switch multi-gang (MVP device #1)
**Status:** Done  
**Dependencies:** S4.2.1 + S5.1.1

**Objetivo:** switch N-gang sem hardcode.

**Tasks**
- T5.1.2.1 Salvar outputs reais:
  - `docs/tuya/<deviceId>_status.json`
  - `docs/tuya/<deviceId>_functions.json`
- T5.1.2.2 Implementar `plugins/tuya/cloud_client.py` (assinatura + request)
- T5.1.2.3 Implementar `plugins/tuya/switch_multigang.py`
  - `describe()` detecta `switch_1..N`
  - `read()` mapeia status codes→state
  - `invoke()` envia command code/value
- T5.1.2.4 Integrar registry (vendor=tuya,type=switch*)
- T5.1.2.5 UI detail mínimo:
  - mostrar toggles para cada `switch_i`

**Acceptance criteria (G/W/T)**
- Given device real multi-gang, When `invoke set_switch channel=1 on=true`, Then tecla 1 liga.
- Given status real, When abrir detail, Then aparecem N toggles coerentes.

**Test plan**
- Manual: ligar/desligar todos canais
- Script: chamar cloud command e revalidar status

**Edge cases**
- gaps: switch_1, switch_2, switch_4 → UI lista somente os existentes
- token expirado → AuthRequired + instrução

---' --label 'roadmap' --label 'story' --label 'epic:E5' --label 'feature:F5.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S5.1.3 — Tuya Smart Plug (power)' --body '### S5.1.3 — Tuya Smart Plug (power)
**Status:** Backlog  
**Dependencies:** S5.1.2 (reuso cloud_client)

**Tasks**
- T5.1.3.1 Descobrir code power via functions/status
- T5.1.3.2 Plugin `smart_plug`
- T5.1.3.3 UI: toggle simples

**Acceptance**
- Liga/desliga tomada real via UI.

---' --label 'roadmap' --label 'story' --label 'epic:E5' --label 'feature:F5.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S5.1.4 — Tuya Light (power/brightness/rgb)' --body '### S5.1.4 — Tuya Light (power/brightness/rgb)
**Status:** Backlog  
**Dependencies:** S5.1.2

**Tasks**
- T5.1.4.1 Mapear codes reais
- T5.1.4.2 Plugin light (invoke power/brightness/color)
- T5.1.4.3 UI: slider + 5 presets de cor

**Acceptance**
- Alterar cor/brilho na vida real.

---' --label 'roadmap' --label 'story' --label 'epic:E5' --label 'feature:F5.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S5.1.5 — Tuya IR + Sensor temp/umidade (climate_sensor_ir)' --body '### S5.1.5 — Tuya IR + Sensor temp/umidade (climate_sensor_ir)
**Status:** Backlog  
**Dependencies:** S5.1.2 + E2 schema

**Tasks**
- T5.1.5.1 Schema `irPresets` em `devices.json`
- T5.1.5.2 Plugin `climate_sensor_ir`
- T5.1.5.3 UI: grid de presets + temp/humidity

**Acceptance**
- Enviar preset IR e atualizar last preset.

---' --label 'roadmap' --label 'story' --label 'epic:E5' --label 'feature:F5.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S5.1.6 — LAN-first Tuya (fase 2)' --body '### S5.1.6 — LAN-first Tuya (fase 2)
**Status:** Backlog  
**Dependencies:** pós-MVP

**Tasks**
- T5.1.6.1 POC tinytuya com local_key
- T5.1.6.2 Fallback LAN→cloud
- T5.1.6.3 Métricas: latência/falhas

---' --label 'roadmap' --label 'story' --label 'epic:E5' --label 'feature:F5.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S5.2.1 — Plugin Winix (stub/lib/api) end-to-end' --body '### S5.2.1 — Plugin Winix (stub/lib/api) end-to-end
**Status:** Done  
**Dependencies:** S4.2.1

**Tasks**
- T5.2.1.1 Refatorar drivers em `plugins/winix/purifier_driver.py`
- T5.2.1.2 `WinixPurifierPlugin` (describe/read/invoke)
- T5.2.1.3 Integrar registry
- T5.2.1.4 UI: power/mode/fan/plasmawave

**Acceptance**
- Comandos executam no purificador real (api/lib).

**Edge cases**
- credenciais ausentes → ConfigError/AuthRequired
- API instável → degrade status e toast coerente

---' --label 'roadmap' --label 'story' --label 'epic:E5' --label 'feature:F5.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.1.1 — Home (pinned + scenes + widgets mínimos)' --body '### S6.1.1 — Home (pinned + scenes + widgets mínimos)
**Status:** Done  
**Dependencies:** E2 configs + E3 executor

**Tasks**
- T6.1.1.1 Quick scenes row
- T6.1.1.2 Pinned devices (grid 2 cols default)
- T6.1.1.3 Room chips filtra home

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.1.2 — Devices (search + filter)' --body '### S6.1.2 — Devices (search + filter)
**Status:** Done  
**Tasks**
- T6.1.2.1 Busca
- T6.1.2.2 Filtro room/status
- T6.1.2.3 Cards por type via registry

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.1.3 — Scenes' --body '### S6.1.3 — Scenes
**Status:** In progress  
**Nota:** UI lista scenes; engine de execução (run_scene) pendente.

**Tasks**
- T6.1.3.1 Lista
- T6.1.3.2 Run com toast agregado

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.1.4 — Rooms' --body '### S6.1.4 — Rooms
**Status:** Done  
**Tasks**
- T6.1.4.1 Overview com contagem online/offline
- T6.1.4.2 Click room → Devices filtrado

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.2.1 — Toast lifecycle + coalesce' --body '### S6.2.1 — Toast lifecycle + coalesce
**Status:** Backlog  
**Tasks**
- T6.2.1.1 Enter/show/leave com animação suave
- T6.2.1.2 TTL e cap (1–2)
- T6.2.1.3 Coalesce por key (scene/activity)

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.2.2 — Menu de configuração (bottom sheet)' --body '### S6.2.2 — Menu de configuração (bottom sheet)
**Status:** Backlog  
**Tasks**
- T6.2.2.1 Abrir/fechar
- T6.2.2.2 Preferências: grid/list, toasts on/off, compact/verbose
- T6.2.2.3 Persist localStorage

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.2.3 — Debug panel (Step zero)' --body '### S6.2.3 — Debug panel (Step zero)
**Status:** Backlog  
**Tasks**
- T6.2.3.1 Last scene/command/error
- T6.2.3.2 Botões: emit toast / run scene / simulate offline

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.2.4 — Bugfix estrutural do UI atual' --body '### S6.2.4 — Bugfix estrutural do UI atual
**Status:** Backlog  
**Observação:** há trecho de menu/config/debug colado dentro de `renderActionEditor()` do `SwitchPanelDetail`, quebrando escopo.

**Tasks**
- T6.2.4.1 Remover bloco menu/config/debug de `renderActionEditor()`
- T6.2.4.2 Reposicionar menu/config/debug no componente root
- T6.2.4.3 Validar build e editor volta a funcionar

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S6.3.1 — GenericControlRenderer' --body '### S6.3.1 — GenericControlRenderer
**Status:** Backlog  
**Tasks**
- T6.3.1.1 Mapear semantic hint → componente
- T6.3.1.2 Render comandos sem UI dedicada

---' --label 'roadmap' --label 'story' --label 'epic:E6' --label 'feature:F6.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S7.1.1 — Delay/retry básicos' --body '### S7.1.1 — Delay/retry básicos
**Status:** Backlog  
**Tasks**
- T7.1.1.1 `delay_ms` em macro steps
- T7.1.1.2 retry com maxAttempts' --label 'roadmap' --label 'story' --label 'epic:E7' --label 'feature:F7.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'S7.2.1 — Vars + if (safe evaluator)' --body '### S7.2.1 — Vars + if (safe evaluator)
**Status:** Backlog  
**Tasks**
- T7.2.1.1 Schema vars
- T7.2.1.2 evaluator sem `eval`

---' --label 'roadmap' --label 'story' --label 'epic:E7' --label 'feature:F7.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T1.1.1.1 Criar pastas: `core/`, `plugins/`, `ui/`, `configs/`, `scripts/`, `docs/adr/`' --body 'Parent: S1.1.1

Criar pastas: `core/`, `plugins/`, `ui/`, `configs/`, `scripts/`, `docs/adr/`' --label 'roadmap' --label 'task' --label 'story:S1.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T1.1.1.2 Criar `README.md` (setup python/node + como rodar)' --body 'Parent: S1.1.1

Criar `README.md` (setup python/node + como rodar)' --label 'roadmap' --label 'task' --label 'story:S1.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T1.1.1.3 Criar `.env.example` (sem valores reais)' --body 'Parent: S1.1.1

Criar `.env.example` (sem valores reais)' --label 'roadmap' --label 'task' --label 'story:S1.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T1.1.1.4 Criar `.gitignore` (env, caches, logs)' --body 'Parent: S1.1.1

Criar `.gitignore` (env, caches, logs)' --label 'roadmap' --label 'task' --label 'story:S1.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T1.2.1.1 Criar `docs/adr/000-template.md`' --body 'Parent: S1.2.1

Criar `docs/adr/000-template.md`' --label 'roadmap' --label 'task' --label 'story:S1.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T1.2.1.2 Criar `docs/adr/001-core-principles.md`' --body 'Parent: S1.2.1

Criar `docs/adr/001-core-principles.md`' --label 'roadmap' --label 'task' --label 'story:S1.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.1.1 Criar `configs/rooms.json` (`id,name,order`)' --body 'Parent: S2.1.1

Criar `configs/rooms.json` (`id,name,order`)' --label 'roadmap' --label 'task' --label 'story:S2.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.1.2 Validar ids únicos no load' --body 'Parent: S2.1.1

Validar ids únicos no load' --label 'roadmap' --label 'task' --label 'story:S2.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.2.1 Criar `configs/devices.json` com:' --body 'Parent: S2.1.2

Criar `configs/devices.json` com:' --label 'roadmap' --label 'task' --label 'story:S2.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.2.2 Documentar enum inicial `type` (README)' --body 'Parent: S2.1.2

Documentar enum inicial `type` (README)' --label 'roadmap' --label 'task' --label 'story:S2.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.2.3 Doc: “como adicionar um device” (README)' --body 'Parent: S2.1.2

Doc: “como adicionar um device” (README)' --label 'roadmap' --label 'task' --label 'story:S2.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.3.1 Criar `configs/scenes.json` (3–4 scenes)' --body 'Parent: S2.1.3

Criar `configs/scenes.json` (3–4 scenes)' --label 'roadmap' --label 'task' --label 'story:S2.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.3.2 Validar referências (deviceId/sceneId)' --body 'Parent: S2.1.3

Validar referências (deviceId/sceneId)' --label 'roadmap' --label 'task' --label 'story:S2.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.3.3 Documentar formato actions (README)' --body 'Parent: S2.1.3

Documentar formato actions (README)' --label 'roadmap' --label 'task' --label 'story:S2.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T2.1.4.1 Criar estrutura runtime cache no backend:' --body 'Parent: S2.1.4

Criar estrutura runtime cache no backend:' --label 'roadmap' --label 'task' --label 'story:S2.1.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.1.1.1 Criar `core/executor.py` com `execute_action`' --body 'Parent: S3.1.1

Criar `core/executor.py` com `execute_action`' --label 'roadmap' --label 'task' --label 'story:S3.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.1.1.2 Logs estruturados (start/end por step)' --body 'Parent: S3.1.1

Logs estruturados (start/end por step)' --label 'roadmap' --label 'task' --label 'story:S3.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.1.1.3 3 testes unitários:' --body 'Parent: S3.1.1

3 testes unitários:' --label 'roadmap' --label 'task' --label 'story:S3.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.1.2.1 Carregar scenes do JSON' --body 'Parent: S3.1.2

Carregar scenes do JSON' --label 'roadmap' --label 'task' --label 'story:S3.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.1.2.2 Validar ids e montar trace' --body 'Parent: S3.1.2

Validar ids e montar trace' --label 'roadmap' --label 'task' --label 'story:S3.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.1.2.3 Retornar payload agregado (`steps_ok/failed/errors[]`)' --body 'Parent: S3.1.2

Retornar payload agregado (`steps_ok/failed/errors[]`)' --label 'roadmap' --label 'task' --label 'story:S3.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.2.1.1 Criar `core/errors.py`: `Offline/Timeout/Unsupported/AuthRequired/ConfigError`' --body 'Parent: S3.2.1

Criar `core/errors.py`: `Offline/Timeout/Unsupported/AuthRequired/ConfigError`' --label 'roadmap' --label 'task' --label 'story:S3.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.2.1.2 Mapper para payload JSON (sem stacktrace cru)' --body 'Parent: S3.2.1

Mapper para payload JSON (sem stacktrace cru)' --label 'roadmap' --label 'task' --label 'story:S3.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.2.1.3 Testes: offline → erro correto' --body 'Parent: S3.2.1

Testes: offline → erro correto' --label 'roadmap' --label 'task' --label 'story:S3.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.3.1.1 Loop a cada N sec: `read(device)` via plugin' --body 'Parent: S3.3.1

Loop a cada N sec: `read(device)` via plugin' --label 'roadmap' --label 'task' --label 'story:S3.3.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.3.1.2 Atualizar runtime cache (last_seen/error)' --body 'Parent: S3.3.1

Atualizar runtime cache (last_seen/error)' --label 'roadmap' --label 'task' --label 'story:S3.3.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T3.3.1.3 Endpoint batch para UI (ex.: `/devices/state`)' --body 'Parent: S3.3.1

Endpoint batch para UI (ex.: `/devices/state`)' --label 'roadmap' --label 'task' --label 'story:S3.3.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.1.1.1 Contrato documentado (ex.: `ADAPTERS/*/CONTRACT.md`)' --body 'Parent: S4.1.1

Contrato documentado (ex.: `ADAPTERS/*/CONTRACT.md`)' --label 'roadmap' --label 'task' --label 'story:S4.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.1.1.2 Mapeamento device → adapter no BACK (isTuyaDevice, isWinixPurifier)' --body 'Parent: S4.1.1

Mapeamento device → adapter no BACK (isTuyaDevice, isWinixPurifier)' --label 'roadmap' --label 'task' --label 'story:S4.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.1.1.3 Stub para testes (TUYA_DRIVER=stub)' --body 'Parent: S4.1.1

Stub para testes (TUYA_DRIVER=stub)' --label 'roadmap' --label 'task' --label 'story:S4.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.1.2.1 Formalizar schema v1 em `docs/protocol_v1.md`' --body 'Parent: S4.1.2

Formalizar schema v1 em `docs/protocol_v1.md`' --label 'roadmap' --label 'task' --label 'story:S4.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.1.2.2 Implementar `describe` em pelo menos um adapter (Tuya)' --body 'Parent: S4.1.2

Implementar `describe` em pelo menos um adapter (Tuya)' --label 'roadmap' --label 'task' --label 'story:S4.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.1.2.3 Migrar BACK router para usar describe (sem hardcode 4 vs 6 gangs)' --body 'Parent: S4.1.2

Migrar BACK router para usar describe (sem hardcode 4 vs 6 gangs)' --label 'roadmap' --label 'task' --label 'story:S4.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.1.2.4 Atualizar UI para consumir commands dinâmicos' --body 'Parent: S4.1.2

Atualizar UI para consumir commands dinâmicos' --label 'roadmap' --label 'task' --label 'story:S4.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.2.1.1 Criar `core/registry.py`' --body 'Parent: S4.2.1

Criar `core/registry.py`' --label 'roadmap' --label 'task' --label 'story:S4.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.2.1.2 Roteamento: device instance → plugin correto' --body 'Parent: S4.2.1

Roteamento: device instance → plugin correto' --label 'roadmap' --label 'task' --label 'story:S4.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T4.2.1.3 Unsupported → erro amigável' --body 'Parent: S4.2.1

Unsupported → erro amigável' --label 'roadmap' --label 'task' --label 'story:S4.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.1.1 `scripts/tuya_cloud_cli.py` no repo' --body 'Parent: S5.1.1

`scripts/tuya_cloud_cli.py` no repo' --label 'roadmap' --label 'task' --label 'story:S5.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.1.2 `docs/tuya/setup.md`: link account, region, token' --body 'Parent: S5.1.1

`docs/tuya/setup.md`: link account, region, token' --label 'roadmap' --label 'task' --label 'story:S5.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.1.3 “Golden commands” no docs (copiar e colar)' --body 'Parent: S5.1.1

“Golden commands” no docs (copiar e colar)' --label 'roadmap' --label 'task' --label 'story:S5.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.2.1 Salvar outputs reais:' --body 'Parent: S5.1.2

Salvar outputs reais:' --label 'roadmap' --label 'task' --label 'story:S5.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.2.2 Implementar `plugins/tuya/cloud_client.py` (assinatura + request)' --body 'Parent: S5.1.2

Implementar `plugins/tuya/cloud_client.py` (assinatura + request)' --label 'roadmap' --label 'task' --label 'story:S5.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.2.3 Implementar `plugins/tuya/switch_multigang.py`' --body 'Parent: S5.1.2

Implementar `plugins/tuya/switch_multigang.py`' --label 'roadmap' --label 'task' --label 'story:S5.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.2.4 Integrar registry (vendor=tuya,type=switch*)' --body 'Parent: S5.1.2

Integrar registry (vendor=tuya,type=switch*)' --label 'roadmap' --label 'task' --label 'story:S5.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.2.5 UI detail mínimo:' --body 'Parent: S5.1.2

UI detail mínimo:' --label 'roadmap' --label 'task' --label 'story:S5.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.3.1 Descobrir code power via functions/status' --body 'Parent: S5.1.3

Descobrir code power via functions/status' --label 'roadmap' --label 'task' --label 'story:S5.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.3.2 Plugin `smart_plug`' --body 'Parent: S5.1.3

Plugin `smart_plug`' --label 'roadmap' --label 'task' --label 'story:S5.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.3.3 UI: toggle simples' --body 'Parent: S5.1.3

UI: toggle simples' --label 'roadmap' --label 'task' --label 'story:S5.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.4.1 Mapear codes reais' --body 'Parent: S5.1.4

Mapear codes reais' --label 'roadmap' --label 'task' --label 'story:S5.1.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.4.2 Plugin light (invoke power/brightness/color)' --body 'Parent: S5.1.4

Plugin light (invoke power/brightness/color)' --label 'roadmap' --label 'task' --label 'story:S5.1.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.4.3 UI: slider + 5 presets de cor' --body 'Parent: S5.1.4

UI: slider + 5 presets de cor' --label 'roadmap' --label 'task' --label 'story:S5.1.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.5.1 Schema `irPresets` em `devices.json`' --body 'Parent: S5.1.5

Schema `irPresets` em `devices.json`' --label 'roadmap' --label 'task' --label 'story:S5.1.5' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.5.2 Plugin `climate_sensor_ir`' --body 'Parent: S5.1.5

Plugin `climate_sensor_ir`' --label 'roadmap' --label 'task' --label 'story:S5.1.5' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.5.3 UI: grid de presets + temp/humidity' --body 'Parent: S5.1.5

UI: grid de presets + temp/humidity' --label 'roadmap' --label 'task' --label 'story:S5.1.5' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.6.1 POC tinytuya com local_key' --body 'Parent: S5.1.6

POC tinytuya com local_key' --label 'roadmap' --label 'task' --label 'story:S5.1.6' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.6.2 Fallback LAN→cloud' --body 'Parent: S5.1.6

Fallback LAN→cloud' --label 'roadmap' --label 'task' --label 'story:S5.1.6' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.1.6.3 Métricas: latência/falhas' --body 'Parent: S5.1.6

Métricas: latência/falhas' --label 'roadmap' --label 'task' --label 'story:S5.1.6' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.2.1.1 Refatorar drivers em `plugins/winix/purifier_driver.py`' --body 'Parent: S5.2.1

Refatorar drivers em `plugins/winix/purifier_driver.py`' --label 'roadmap' --label 'task' --label 'story:S5.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.2.1.2 `WinixPurifierPlugin` (describe/read/invoke)' --body 'Parent: S5.2.1

`WinixPurifierPlugin` (describe/read/invoke)' --label 'roadmap' --label 'task' --label 'story:S5.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.2.1.3 Integrar registry' --body 'Parent: S5.2.1

Integrar registry' --label 'roadmap' --label 'task' --label 'story:S5.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T5.2.1.4 UI: power/mode/fan/plasmawave' --body 'Parent: S5.2.1

UI: power/mode/fan/plasmawave' --label 'roadmap' --label 'task' --label 'story:S5.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.1.1 Quick scenes row' --body 'Parent: S6.1.1

Quick scenes row' --label 'roadmap' --label 'task' --label 'story:S6.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.1.2 Pinned devices (grid 2 cols default)' --body 'Parent: S6.1.1

Pinned devices (grid 2 cols default)' --label 'roadmap' --label 'task' --label 'story:S6.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.1.3 Room chips filtra home' --body 'Parent: S6.1.1

Room chips filtra home' --label 'roadmap' --label 'task' --label 'story:S6.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.2.1 Busca' --body 'Parent: S6.1.2

Busca' --label 'roadmap' --label 'task' --label 'story:S6.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.2.2 Filtro room/status' --body 'Parent: S6.1.2

Filtro room/status' --label 'roadmap' --label 'task' --label 'story:S6.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.2.3 Cards por type via registry' --body 'Parent: S6.1.2

Cards por type via registry' --label 'roadmap' --label 'task' --label 'story:S6.1.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.3.1 Lista' --body 'Parent: S6.1.3

Lista' --label 'roadmap' --label 'task' --label 'story:S6.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.3.2 Run com toast agregado' --body 'Parent: S6.1.3

Run com toast agregado' --label 'roadmap' --label 'task' --label 'story:S6.1.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.4.1 Overview com contagem online/offline' --body 'Parent: S6.1.4

Overview com contagem online/offline' --label 'roadmap' --label 'task' --label 'story:S6.1.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.1.4.2 Click room → Devices filtrado' --body 'Parent: S6.1.4

Click room → Devices filtrado' --label 'roadmap' --label 'task' --label 'story:S6.1.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.1.1 Enter/show/leave com animação suave' --body 'Parent: S6.2.1

Enter/show/leave com animação suave' --label 'roadmap' --label 'task' --label 'story:S6.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.1.2 TTL e cap (1–2)' --body 'Parent: S6.2.1

TTL e cap (1–2)' --label 'roadmap' --label 'task' --label 'story:S6.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.1.3 Coalesce por key (scene/activity)' --body 'Parent: S6.2.1

Coalesce por key (scene/activity)' --label 'roadmap' --label 'task' --label 'story:S6.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.2.1 Abrir/fechar' --body 'Parent: S6.2.2

Abrir/fechar' --label 'roadmap' --label 'task' --label 'story:S6.2.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.2.2 Preferências: grid/list, toasts on/off, compact/verbose' --body 'Parent: S6.2.2

Preferências: grid/list, toasts on/off, compact/verbose' --label 'roadmap' --label 'task' --label 'story:S6.2.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.2.3 Persist localStorage' --body 'Parent: S6.2.2

Persist localStorage' --label 'roadmap' --label 'task' --label 'story:S6.2.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.3.1 Last scene/command/error' --body 'Parent: S6.2.3

Last scene/command/error' --label 'roadmap' --label 'task' --label 'story:S6.2.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.3.2 Botões: emit toast / run scene / simulate offline' --body 'Parent: S6.2.3

Botões: emit toast / run scene / simulate offline' --label 'roadmap' --label 'task' --label 'story:S6.2.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.4.1 Remover bloco menu/config/debug de `renderActionEditor()`' --body 'Parent: S6.2.4

Remover bloco menu/config/debug de `renderActionEditor()`' --label 'roadmap' --label 'task' --label 'story:S6.2.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.4.2 Reposicionar menu/config/debug no componente root' --body 'Parent: S6.2.4

Reposicionar menu/config/debug no componente root' --label 'roadmap' --label 'task' --label 'story:S6.2.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.2.4.3 Validar build e editor volta a funcionar' --body 'Parent: S6.2.4

Validar build e editor volta a funcionar' --label 'roadmap' --label 'task' --label 'story:S6.2.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.3.1.1 Mapear semantic hint → componente' --body 'Parent: S6.3.1

Mapear semantic hint → componente' --label 'roadmap' --label 'task' --label 'story:S6.3.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T6.3.1.2 Render comandos sem UI dedicada' --body 'Parent: S6.3.1

Render comandos sem UI dedicada' --label 'roadmap' --label 'task' --label 'story:S6.3.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T7.1.1.1 `delay_ms` em macro steps' --body 'Parent: S7.1.1

`delay_ms` em macro steps' --label 'roadmap' --label 'task' --label 'story:S7.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T7.1.1.2 retry com maxAttempts' --body 'Parent: S7.1.1

retry com maxAttempts' --label 'roadmap' --label 'task' --label 'story:S7.1.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T7.2.1.1 Schema vars' --body 'Parent: S7.2.1

Schema vars' --label 'roadmap' --label 'task' --label 'story:S7.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T7.2.1.2 evaluator sem `eval`' --body 'Parent: S7.2.1

evaluator sem `eval`' --label 'roadmap' --label 'task' --label 'story:S7.2.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.1.1 Checar API oficial/local' --body 'Parent: F8.1

Checar API oficial/local' --label 'roadmap' --label 'task' --label 'feature:F8.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.1.2 Se RE: mapear auth/replay/binding' --body 'Parent: F8.1

Se RE: mapear auth/replay/binding' --label 'roadmap' --label 'task' --label 'feature:F8.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.1.3 Go/No-go doc' --body 'Parent: F8.1

Go/No-go doc' --label 'roadmap' --label 'task' --label 'feature:F8.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.3.1 Branch POC “vertical”' --body 'Parent: F8.3

Branch POC “vertical”' --label 'roadmap' --label 'task' --label 'feature:F8.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.3.2 Implementar tuya_switch em layout vertical' --body 'Parent: F8.3

Implementar tuya_switch em layout vertical' --label 'roadmap' --label 'task' --label 'feature:F8.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.3.3 Comparar delta de mudança' --body 'Parent: F8.3

Comparar delta de mudança' --label 'roadmap' --label 'task' --label 'feature:F8.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.3.4 ADR de recomendação' --body 'Parent: F8.3

ADR de recomendação' --label 'roadmap' --label 'task' --label 'feature:F8.3' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.4.1 Formalizar spec `describe/read/invoke` v0' --body 'Parent: F8.4

Formalizar spec `describe/read/invoke` v0' --label 'roadmap' --label 'task' --label 'feature:F8.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.4.2 POC com tuya_switch' --body 'Parent: F8.4

POC com tuya_switch' --label 'roadmap' --label 'task' --label 'feature:F8.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.4.3 Medir redução de mudanças no backend' --body 'Parent: F8.4

Medir redução de mudanças no backend' --label 'roadmap' --label 'task' --label 'feature:F8.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T8.4.4 Recomendação (adotar/não/partial)' --body 'Parent: F8.4

Recomendação (adotar/não/partial)' --label 'roadmap' --label 'task' --label 'feature:F8.4' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T10.1.1 Log de cada invoke/scene' --body 'Parent: F10.1

Log de cada invoke/scene' --label 'roadmap' --label 'task' --label 'feature:F10.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T10.1.2 Export JSON' --body 'Parent: F10.1

Export JSON' --label 'roadmap' --label 'task' --label 'feature:F10.1' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T10.2.1 Mask tokens em logs' --body 'Parent: F10.2

Mask tokens em logs' --label 'roadmap' --label 'task' --label 'feature:F10.2' --project 'SmarterHome-Project'
gh issue create -R 'Arrow-Head-Tech/SMARTER_HOME' --title 'T10.2.2 Checagem CI “.env não commit”' --body 'Parent: F10.2

Checagem CI “.env não commit”' --label 'roadmap' --label 'task' --label 'feature:F10.2' --project 'SmarterHome-Project'